project_id = "sggvzsewumgdhigdhcqp"

[functions.send-push-notification]
verify_jwt = false

[functions.woocommerce-webhook]
verify_jwt = false

[functions.send-order-notifications]
verify_jwt = false

[functions.google-places-autocomplete]
verify_jwt = false

[functions.cardcom-create-payment]
verify_jwt = false

[functions.payplus-create-payment]
verify_jwt = false

[functions.notify-customer-message]
verify_jwt = false

[functions.parse-repair-request]
verify_jwt = false

[functions.customer-auth]
verify_jwt = false

[functions.send-technician-application]
verify_jwt = false