project_id = "sggvzsewumgdhigdhcqp"

[functions.send-push-notification]
verify_jwt = false

[functions.woocommerce-webhook]
verify_jwt = false

[functions.send-order-notifications]
verify_jwt = false

[functions.google-places-autocomplete]
verify_jwt = false