export interface StoreProduct {
  id: string;
  name: string;
  description: string;
  price: number;
  pointsPrice?: number; // can buy with points
  image: string;
  category: 'iphones' | 'cases' | 'chargers' | 'audio' | 'protection';
  badge?: string;
  specs?: string[];
  colors?: string[];
  inStock: boolean;
}

export interface CartItem {
  product: StoreProduct;
  quantity: number;
  selectedColor?: string;
}

export const storeCategories = [
  { slug: 'iphones', name: 'אייפונים', icon: 'Smartphone' },
  { slug: 'cases', name: 'כיסויים', icon: 'Shield' },
  { slug: 'chargers', name: 'מטענים וכבלים', icon: 'Zap' },
  { slug: 'audio', name: 'אוזניות ושמע', icon: 'Headphones' },
  { slug: 'protection', name: 'מגנים וזכוכיות', icon: 'ShieldCheck' },
] as const;

export const storeProducts: StoreProduct[] = [
  // iPhones
  {
    id: 'iphone-15',
    name: 'iPhone 15',
    description: 'מסך Super Retina XDR בגודל 6.1 אינץ׳, שבב A16 Bionic, מצלמה כפולה 48MP, USB-C, זיהוי פנים',
    price: 3299,
    image: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-15-finish-select-202309-6-1inch-blue?wid=400&hei=400&fmt=jpeg',
    category: 'iphones',
    badge: 'פופולרי',
    specs: ['6.1" Super Retina XDR', 'A16 Bionic', '48MP מצלמה', 'USB-C'],
    colors: ['כחול', 'ורוד', 'ירוק', 'שחור', 'צהוב'],
    inStock: true,
  },
  {
    id: 'iphone-15-pro',
    name: 'iPhone 15 Pro',
    description: 'מסך Super Retina XDR בגודל 6.1 אינץ׳, שבב A17 Pro, מצלמה משולשת 48MP, טיטניום, Action Button',
    price: 4499,
    image: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-15-pro-finish-select-202309-6-1inch-naturaltitanium?wid=400&hei=400&fmt=jpeg',
    category: 'iphones',
    badge: 'Pro',
    specs: ['6.1" Super Retina XDR', 'A17 Pro', '48MP מצלמה משולשת', 'טיטניום'],
    colors: ['טיטניום טבעי', 'טיטניום כחול', 'טיטניום לבן', 'טיטניום שחור'],
    inStock: true,
  },
  {
    id: 'iphone-15-pro-max',
    name: 'iPhone 15 Pro Max',
    description: 'מסך Super Retina XDR בגודל 6.7 אינץ׳, שבב A17 Pro, מצלמת טלפוטו 5x, טיטניום',
    price: 5199,
    image: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-15-pro-finish-select-202309-6-7inch-naturaltitanium?wid=400&hei=400&fmt=jpeg',
    category: 'iphones',
    specs: ['6.7" Super Retina XDR', 'A17 Pro', '5x Telephoto', 'טיטניום'],
    colors: ['טיטניום טבעי', 'טיטניום כחול', 'טיטניום לבן', 'טיטניום שחור'],
    inStock: true,
  },
  {
    id: 'iphone-16',
    name: 'iPhone 16',
    description: 'מסך Super Retina XDR בגודל 6.1 אינץ׳, שבב A18, מצלמה כפולה 48MP, Camera Control, Apple Intelligence',
    price: 3599,
    image: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-16-finish-select-202409-6-1inch-ultramarine?wid=400&hei=400&fmt=jpeg',
    category: 'iphones',
    badge: 'חדש',
    specs: ['6.1" Super Retina XDR', 'A18', '48MP Fusion Camera', 'Apple Intelligence'],
    colors: ['אולטרמרין', 'ירקרק', 'ורוד', 'לבן', 'שחור'],
    inStock: true,
  },
  {
    id: 'iphone-16-pro',
    name: 'iPhone 16 Pro',
    description: 'מסך Super Retina XDR בגודל 6.3 אינץ׳, שבב A18 Pro, מצלמת Fusion 48MP, 4K120fps, טיטניום',
    price: 4799,
    image: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-16-pro-finish-select-202409-6-3inch-deserttitanium?wid=400&hei=400&fmt=jpeg',
    category: 'iphones',
    badge: 'Pro',
    specs: ['6.3" Super Retina XDR', 'A18 Pro', '48MP Fusion', '4K120fps'],
    colors: ['טיטניום מדבר', 'טיטניום טבעי', 'טיטניום לבן', 'טיטניום שחור'],
    inStock: true,
  },
  {
    id: 'iphone-16-pro-max',
    name: 'iPhone 16 Pro Max',
    description: 'מסך Super Retina XDR בגודל 6.9 אינץ׳, שבב A18 Pro, מצלמת Tetraprism 5x, סוללת השיא',
    price: 5499,
    image: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-16-pro-finish-select-202409-6-9inch-deserttitanium?wid=400&hei=400&fmt=jpeg',
    category: 'iphones',
    badge: 'הדגל',
    specs: ['6.9" Super Retina XDR', 'A18 Pro', '5x Tetraprism', 'סוללת השיא'],
    colors: ['טיטניום מדבר', 'טיטניום טבעי', 'טיטניום לבן', 'טיטניום שחור'],
    inStock: true,
  },
  {
    id: 'iphone-17-pro',
    name: 'iPhone 17 Pro',
    description: 'הדור הבא של אפל - שבב A19 Pro, מצלמת 48MP משודרגת, עיצוב חדשני, Apple Intelligence מתקדם',
    price: 4999,
    image: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-16-pro-finish-select-202409-6-3inch-naturaltitanium?wid=400&hei=400&fmt=jpeg',
    category: 'iphones',
    badge: '🔥 2025',
    specs: ['6.3" ProMotion', 'A19 Pro', '48MP Advanced', 'Apple Intelligence 2.0'],
    colors: ['טיטניום', 'שחור', 'לבן', 'ירוק כהה'],
    inStock: true,
  },
  // Cases
  {
    id: 'case-silicone-15',
    name: 'כיסוי סיליקון iPhone 15',
    description: 'כיסוי סיליקון מקורי עם MagSafe, מגע רך ונעים, הגנה מלאה',
    price: 149,
    pointsPrice: 300,
    image: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MT393ZM_A?wid=400&hei=400&fmt=jpeg',
    category: 'cases',
    colors: ['כחול ערפל', 'ציפרס', 'שחקים', 'חימר'],
    inStock: true,
  },
  {
    id: 'case-leather-16',
    name: 'כיסוי עור iPhone 16 Pro',
    description: 'כיסוי עור פרימיום, עיצוב אלגנטי עם MagSafe מובנה',
    price: 249,
    pointsPrice: 500,
    image: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MA7M3ZM_A?wid=400&hei=400&fmt=jpeg',
    category: 'cases',
    badge: 'פרימיום',
    colors: ['שחור', 'חום', 'כחול כהה'],
    inStock: true,
  },
  {
    id: 'case-clear-16',
    name: 'כיסוי שקוף MagSafe',
    description: 'כיסוי שקוף עם MagSafe, מציג את צבע המכשיר המקורי',
    price: 129,
    pointsPrice: 250,
    image: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MHLL3ZM_A?wid=400&hei=400&fmt=jpeg',
    category: 'cases',
    inStock: true,
  },
  {
    id: 'case-rugged',
    name: 'כיסוי שטח מוקשח',
    description: 'הגנה מקסימלית מפני נפילות, עמיד בתקן צבאי MIL-STD-810G',
    price: 179,
    pointsPrice: 350,
    image: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MQUD3ZM_A?wid=400&hei=400&fmt=jpeg',
    category: 'cases',
    badge: 'הגנה מקסימלית',
    colors: ['שחור', 'ירוק צבאי', 'כתום'],
    inStock: true,
  },
  // Chargers
  {
    id: 'magsafe-charger',
    name: 'מטען MagSafe',
    description: 'טעינה אלחוטית מהירה עד 15W עם חיבור מגנטי מושלם',
    price: 169,
    pointsPrice: 350,
    image: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MHXH3?wid=400&hei=400&fmt=jpeg',
    category: 'chargers',
    inStock: true,
  },
  {
    id: 'usbc-cable',
    name: 'כבל USB-C ל-USB-C (2m)',
    description: 'כבל USB-C קלוע באורך 2 מטר, תומך טעינה מהירה',
    price: 89,
    pointsPrice: 180,
    image: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MU2G3?wid=400&hei=400&fmt=jpeg',
    category: 'chargers',
    inStock: true,
  },
  {
    id: 'power-adapter-20w',
    name: 'מתאם חשמל 20W USB-C',
    description: 'מתאם טעינה מהירה 20W, טעינה עד 50% ב-30 דקות',
    price: 109,
    pointsPrice: 220,
    image: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MHJA3?wid=400&hei=400&fmt=jpeg',
    category: 'chargers',
    inStock: true,
  },
  {
    id: 'powerbank-magsafe',
    name: 'סוללה חיצונית MagSafe',
    description: 'סוללה חיצונית מגנטית 5000mAh, מתחברת ישירות למכשיר',
    price: 249,
    pointsPrice: 500,
    image: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MJWY3?wid=400&hei=400&fmt=jpeg',
    category: 'chargers',
    badge: 'חובה',
    inStock: true,
  },
  // Audio
  {
    id: 'airpods-4',
    name: 'AirPods 4',
    description: 'אוזניות אלחוטיות עם שבב H2, שמע מרחבי, עמידות למים IPX4',
    price: 549,
    pointsPrice: 1100,
    image: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/airpods-4-hero-select-202409?wid=400&hei=400&fmt=jpeg',
    category: 'audio',
    badge: 'חדש',
    inStock: true,
  },
  {
    id: 'airpods-pro-2',
    name: 'AirPods Pro 2',
    description: 'ביטול רעשים אקטיבי, שבב H2, USB-C, שמע מרחבי מותאם אישית',
    price: 899,
    pointsPrice: 1800,
    image: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MQD83?wid=400&hei=400&fmt=jpeg',
    category: 'audio',
    badge: 'בסט סלר',
    inStock: true,
  },
  {
    id: 'airpods-max',
    name: 'AirPods Max',
    description: 'אוזניות Over-Ear פרימיום, ביטול רעשים יוצא דופן, שמע High-Fidelity',
    price: 2199,
    image: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/airpods-max-select-202409-midnight?wid=400&hei=400&fmt=jpeg',
    category: 'audio',
    badge: 'פרימיום',
    colors: ['לילה', 'כוכבים', 'כחול', 'כתום', 'סגול'],
    inStock: true,
  },
  // Protection
  {
    id: 'screen-protector-15',
    name: 'מגן מסך זכוכית iPhone 15/16',
    description: 'זכוכית מחוסמת 9H עם ציפוי אולאופובי, התקנה קלה עם מסגרת',
    price: 49,
    pointsPrice: 100,
    image: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MU053?wid=400&hei=400&fmt=jpeg',
    category: 'protection',
    inStock: true,
  },
  {
    id: 'screen-protector-pro',
    name: 'מגן מסך פרייבסי iPhone Pro',
    description: 'מגן מסך עם פילטר פרטיות, נראה רק מלפנים, 9H',
    price: 79,
    pointsPrice: 160,
    image: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MU073?wid=400&hei=400&fmt=jpeg',
    category: 'protection',
    badge: 'פרטיות',
    inStock: true,
  },
  {
    id: 'camera-protector',
    name: 'מגן מצלמה זכוכית',
    description: 'הגנת זכוכית ספיר למצלמה, שקיפות מלאה ללא פגיעה באיכות התמונה',
    price: 39,
    pointsPrice: 80,
    image: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MU0F3?wid=400&hei=400&fmt=jpeg',
    category: 'protection',
    inStock: true,
  },
];
